// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// unitize_C
arma::mat unitize_C(arma::mat weight);
RcppExport SEXP _MERINGUE_unitize_C(SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(unitize_C(weight));
    return rcpp_result_gen;
END_RCPP
}
// spatialCrossCor_C
double spatialCrossCor_C(arma::vec x, arma::vec y, arma::mat weight);
RcppExport SEXP _MERINGUE_spatialCrossCor_C(SEXP xSEXP, SEXP ySEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(spatialCrossCor_C(x, y, weight));
    return rcpp_result_gen;
END_RCPP
}
// spatialCrossCorMatrix_C
arma::mat spatialCrossCorMatrix_C(arma::mat sigMat, arma::mat weight, bool display_progress);
RcppExport SEXP _MERINGUE_spatialCrossCorMatrix_C(SEXP sigMatSEXP, SEXP weightSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type sigMat(sigMatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(spatialCrossCorMatrix_C(sigMat, weight, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// moranTest_C
arma::vec moranTest_C(arma::vec x, arma::mat weight);
RcppExport SEXP _MERINGUE_moranTest_C(SEXP xSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(moranTest_C(x, weight));
    return rcpp_result_gen;
END_RCPP
}
// getSpatialPatterns_C
arma::mat getSpatialPatterns_C(arma::mat mat, arma::mat adj, bool display_progress);
RcppExport SEXP _MERINGUE_getSpatialPatterns_C(SEXP matSEXP, SEXP adjSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mat(matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(getSpatialPatterns_C(mat, adj, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MERINGUE_unitize_C", (DL_FUNC) &_MERINGUE_unitize_C, 1},
    {"_MERINGUE_spatialCrossCor_C", (DL_FUNC) &_MERINGUE_spatialCrossCor_C, 3},
    {"_MERINGUE_spatialCrossCorMatrix_C", (DL_FUNC) &_MERINGUE_spatialCrossCorMatrix_C, 3},
    {"_MERINGUE_moranTest_C", (DL_FUNC) &_MERINGUE_moranTest_C, 2},
    {"_MERINGUE_getSpatialPatterns_C", (DL_FUNC) &_MERINGUE_getSpatialPatterns_C, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MERINGUE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
