# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unitize_C <- function(weight) {
    .Call('_MERingue_unitize_C', PACKAGE = 'MERingue', weight)
}

spatialCrossCor_C <- function(x, y, weight) {
    .Call('_MERingue_spatialCrossCor_C', PACKAGE = 'MERingue', x, y, weight)
}

spatialCrossCorMatrix_C <- function(sigMat, weight) {
    .Call('_MERingue_spatialCrossCorMatrix_C', PACKAGE = 'MERingue', sigMat, weight)
}

moranTest_C <- function(x, weight) {
    .Call('_MERingue_moranTest_C', PACKAGE = 'MERingue', x, weight)
}

getSpatialPatterns_C <- function(mat, adj) {
    .Call('_MERingue_getSpatialPatterns_C', PACKAGE = 'MERingue', mat, adj)
}

