# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unitize_C <- function(weight) {
    .Call('_MERINGUE_unitize_C', PACKAGE = 'MERINGUE', weight)
}

spatialCrossCor_C <- function(x, y, weight) {
    .Call('_MERINGUE_spatialCrossCor_C', PACKAGE = 'MERINGUE', x, y, weight)
}

spatialCrossCorMatrix_C <- function(sigMat, weight, display_progress = TRUE) {
    .Call('_MERINGUE_spatialCrossCorMatrix_C', PACKAGE = 'MERINGUE', sigMat, weight, display_progress)
}

moranTest_C <- function(x, weight) {
    .Call('_MERINGUE_moranTest_C', PACKAGE = 'MERINGUE', x, weight)
}

getSpatialPatterns_C <- function(mat, adj, display_progress = TRUE) {
    .Call('_MERINGUE_getSpatialPatterns_C', PACKAGE = 'MERINGUE', mat, adj, display_progress)
}

